### PR TITLE
Broken formulas cleanup

### PR DESCRIPTION
**Pull request by sbesson**
This PR cleans up broken formulas in this tap and  fix Travis.  The `zeroc-ice` formula are dropped in favor of the official https://github.com/zeroc-ice/homebrew-tap tap. The `omero` formula are irreversibly broken given changes to the Homebrew build strategy.

The build should now be green and test the installation of the `bioformats` formula. Internally this also means we should be able to drop the [Bio-Formats Homebrew job](https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-homebrew/) job and use exclusively Travis for validation.

/cc @dgault @joshmoore @jburel

### CODE REVIEW

**Comment by joshmoore** [comment]
Following on from https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7853#p19103 I tried `brew install ome/alt/zeroc-ice35 --with-python` this morning which fails with:

```
==> Downloading http://download.oracle.com/berkeley-db/db-5.3.28.tar.gz
Already downloaded: /Users/jamoore/Library/Caches/Homebrew/zeroc-ice35--berkeley-db-5.3.28.tar.gz
==> ../dist/configure --disable-debug --prefix=/usr/local/Cellar/zeroc-ice35/3.5.1_1/libexec --mandir=/usr/local/Cellar/zeroc-ice35/3.5
==> make install
==> make prefix=/usr/local/Cellar/zeroc-ice35/3.5.1_1 install_mandir=/usr/local/Cellar/zeroc-ice35/3.5.1_1/share/man/man1 install_slice
==> make install prefix=/usr/local/Cellar/zeroc-ice35/3.5.1_1 install_mandir=/usr/local/Cellar/zeroc-ice35/3.5.1_1/share/man/man1 insta
==> make prefix=/usr/local/Cellar/zeroc-ice35/3.5.1_1 install_mandir=/usr/local/Cellar/zeroc-ice35/3.5.1_1/share/man/man1 install_slice
==> make install prefix=/usr/local/Cellar/zeroc-ice35/3.5.1_1 install_mandir=/usr/local/Cellar/zeroc-ice35/3.5.1_1/share/man/man1 insta
==> make prefix=/usr/local/Cellar/zeroc-ice35/3.5.1_1 install_mandir=/usr/local/Cellar/zeroc-ice35/3.5.1_1/share/man/man1 install_slice
Last 15 lines from /Users/jamoore/Library/Logs/Homebrew/zeroc-ice35/07.make:
        if(PyTuple_SET_ITEM(args.get(), 0, (PyObject*)obj) < 0) // PyTuple_SET_ITEM steals a reference.
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
Operation.cpp:3665:54: error: ordered comparison between pointer and zero ('PyObject *' (aka '_object *') and 'int')
    if(PyTuple_SET_ITEM(args.get(), start, ip.get()) < 0)
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
Operation.cpp:3677:56: error: ordered comparison between pointer and zero ('PyObject *' (aka '_object *') and 'int')
    if(PyTuple_SET_ITEM(args.get(), start, curr.get()) < 0)
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
Operation.cpp:3697:60: error: ordered comparison between pointer and zero ('PyObject *' (aka '_object *') and 'int')
        if(PyTuple_SET_ITEM(args.get(), 0, (PyObject*)obj) < 0) // PyTuple_SET_ITEM steals a reference.
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
15 errors generated.
make[2]: *** [Operation.o] Error 1
make[1]: *** [all] Error 1
make: *** [all] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ome/homebrew-alt/issues
```

Happy to file this as an issue but equally happy to remove the broken and dependent formulae here if we're dropping testing from travis.

**Comment by sbesson** [comment]
My understanding is that many of our formulas are broken for different reasons. Proposal would be to move forward with the cleanup suggested in the description and @joshmoore's comment with the following rationales:

- `zeroc-ice{33,34,35}`: OME maintaining the distribution for an external dependency was really a workaround in the early days. Propose to remove in favor of https://github.com/zeroc-ice/homebrew-tap since the ZeroC team is now maintaining its own tap.
- `berkeley-db{44,45}` are dependencies of `zeroc-ice` and the ZeroC tap also implements them.
- `omero{43,44,50,51,52,53}`  are broken since Homebrew switched to impose sandboxing for building (so the `~/.m2` directory cannot be used)

**Comment by joshmoore** [comment]
Quite the cleanup, but 💚 Assuming the disappearance won't cause any unintended side-effects, I think this is (unfortunately) our best choice currently.

**Comment by dgault** [comment]
The Travis build for Bio-Formats is now working as expected and the Bio-Formats install completes successfully with the installation of the correct version (5.8.0). The Bio-Formats test completes as expected with showinf and bfconvert tested. The updated documentation also looks good.

As far as removing the broken OMERO, zeroc-ice and berkley-db formulas, this is fine from my perspective if there is no easy way of getting the OMERO formulas working currently.

PR is good from my side.

**Comment by sbesson** [comment]
Thanks all. Merging and actioning the removal of the CI jobs.

**Pull request merged**
