### PR TITLE
Bump OMERO formulas to 5.1.0-m4

### PR DESCRIPTION
**Pull request by sbesson**
Also remove Bio-Formats version patching for OMERO formula

### CODE REVIEW

**Comment by joshmoore** [comment]
https://ci.openmicroscopy.org/job/OME-5.1-merge-homebrew/ICE=3.5,OSX=snapper/49/ :thumbsup:

**Comment by sbesson** [comment]
ONly issue mentioned in the Trello card is the version subsitution logic

```
2015-02-19 10:42:40,542 1093       [      main] INFO          ome.formats.importer.ImportConfig - OMERO Version: 5.1.0-m4-ice35
2015-02-19 10:42:40,643 1194       [      main] INFO          ome.formats.importer.ImportConfig - Bioformats version: 5.1.0-DEV revision: 51bf71d date: 19 February 2015
```

Should I patch this formula or is it okay to leave as it is (and fix for 5.1.0)?

**Comment by joshmoore** [comment]
I'm not overly concerned to be honest.

**Comment by sbesson** [comment]
Since we'll rebuild `m4` I'll try to have that fixed as part of the release process

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/OME-5.1-merge-homebrew/51/

**Comment by joshmoore** [comment]
:thumbsup:

**Pull request merged**
