### PR TITLE
Package Bio-Formats C++ library and tests

### PR DESCRIPTION
**Pull request by rleigh-dundee**
Build and install the 5.1.0-m4 release.

See also: https://github.com/Homebrew/homebrew-science/compare/master...rleigh-dundee:bfcpp?expand=1 (waiting on final release)

--------

Testing:

```
brew install bioformats-cpp51 --with-qt5
showinf --help
glview
```

(This will use `bf-test info|view` with m5)

### CODE REVIEW

**Comment by sbesson** [comment]
Travis is failing for unrelated reasons (will fix the audit in another PR). Is it worth adding this formula to https://github.com/ome/omero-install/blob/master/homebrew/install_omero51 so that we test it on a daily basis?

**Comment by rleigh-dundee** [comment]
@sbesson It's certainly worth adding if we want to test this regularly; OTOH it's not covering anything which isn't already in the existing merge/latest jobs so other than testing the formula is OK it's not particularly exciting or directly beneficial.  Would a separate job which just tests the final release zip e.g. weekly be a better use of our resources?

**Comment by sbesson** [comment]
I think the goal of the daily/weekly Homebrew Ci job is orthogonal to the goal of merge/latest jobs which are mostly for development purposes. Here the idea is rather to check the deployment and validity of release formulas against either OS X platform updates or upstream Homebrew modifications. As you said, nothing particular exciting but if we start using Homebrew as a distribution tool, this will allow us to catch bugs early.

**Comment by rleigh-dundee** [comment]
@sbesson Agreed, my only question is whether daily is too frequent for its relative importance.  Also, should this be a separate jenkins job; why would we want to couple it to the existing tests?  Won't that make catching missing dependencies more difficult since it's not being tested alone?

**Comment by sbesson** [comment]
The cost of running daily is at the moment extremely low since given the usage of this box but I have no major objection to decreasing the frequency. Having a separate Jenkins job would also makes sense. With https://github.com/ome/omero-install/pull/11 we now have all the infrastructure for installing Homebrew and merging formula PRs independently of the formula installation per se. So, opening a PR to separate the OMERO from the Bio-Formats installation in `install_omero51` would be the first step towards automation of this testing.

**Comment by manics** [comment]
What's happening with this PR?

**Comment by joshmoore** [comment]
Ping @rleigh-dundee / @sbesson

**Comment by sbesson** [comment]
As mentioned on https://github.com/ome/homebrew-alt/pull/74#issuecomment-82843374, the most straightforward to test this PR now is to test this formula immediately is to open a PR against `omero-install`. The alternative suggested in https://github.com/ome/homebrew-alt/pull/74#issuecomment-82914411 was to set up a separate job which is achievable but requires decisions on:
- the name/frequency for the job
- the location of the testing script (note `omero-install` has a lot of logic under `install_homebrew`)

**Comment by rleigh-dundee** [comment]
Nothing new to add.  I would prefer to add a separate job rather than unnecessarily couple it to omero.  Part of the point of testing it is to ensure the dependencies are correct, and coupling it will not test that effectively.

**Comment by joshmoore** [comment]
Discussion: new job BIOFORMATS-homebrew-* will be created using https://github.com/ome/omero-install/blob/master/homebrew/install_homebrew and this PR will be updated to use 5.1.2 (this will become a regular release step)

**Comment by rleigh-dundee** [comment]
@joshmoore Updated for 5.1.2.

**Comment by joshmoore** [comment]
Currently on:
```
==> Installing bioformats-cpp51
==> Downloading http://downloads.openmicroscopy.org/bio-formats/5.1.2/artifacts/bioformats-5.1.2.zip
```

**Comment by rleigh-dundee** [comment]
@joshmoore Just pushed a minor tweak to the testing; I didn't realise the test stuff provided by brew was post-installation only, so swapped that back to run tests before install.

**Comment by joshmoore** [comment]
Got 'em:
```
Testing bioformats-cpp51
==> bf-test --usage
==> bf-test info --usage
```

:thumbsup:

Two minor unrelated RFEs:
 * `bin/omero export $X -f $X.ome.tiff && bf-test info $X.ome.tiff` produces `[2015-05-28 14:54:51.277690] [0x00007fff78c11300] [warning] UUID filename "__omero_export__2098578392266161640.ome.tiff" not found; falling back to "/private/tmp/Day 2 Chitin Kan.ome.tiff"`
 * `tiffcomment $X.ome.tiff > $X.ome.xml && bf-test info $X.ome.xml` produces `E: /private/tmp/Day 2 Chitin Kan.ome.xml: Not a TIFF or MDI file, bad magic number 16188 (0x3f3c)`

**Comment by rleigh-dundee** [comment]
For the warning, that's expected and intentional--the metadata is inconsistent and while we make a good effort to read broken OME-TIFFs, this could result in incorrect behaviour if the assumptions made don't hold, e.g. reading IFDs from the wrong TIFF file, so I think logging a warning is appropriate in this case, since we can't guarantee the pixel data is correct.

For the ome.xml case, we have tickets for adding an OME-XML reader and writer.  bf-info is currently hardcoded to use OME-TIFF only for reading; there's tickets for ImageReader and ImageWriter as well for that.

**Comment by joshmoore** [comment]
Comparing showinf(java)'s behavior, guess there's not much room for argument:
```
$ bftools/showinf Day\ 2\ Chitin\ Kan.ome.xml
Exception in thread "main" loci.formats.UnknownFormatException: Unknown file format: Day 2 Chitin Kan.ome.xml
        at loci.formats.ImageReader.getReader(ImageReader.java:190)
        at loci.formats.ImageReader.getFormat(ImageReader.java:152)
        at loci.formats.tools.ImageInfo.configureReaderPreInit(ImageInfo.java:414)
        at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1007)
        at loci.formats.tools.ImageInfo.main(ImageInfo.java:1100)
```

**Comment by joshmoore** [comment]
I slightly disagree with the first of these two, and once bf++ is in production, would err on the side of matching the behavior on the Java side. But that can be discussed elsewhere. It was mostly just my first natively installed experience. :smile: Thanks.

**Comment by rleigh-dundee** [comment]
@joshmoore We can certainly discuss that further and it can certainly be made configurable.  Note that on the Java side it has been swallowing serious errors for many years, even when the OME-XML is totally invalid, which is going too far the other way.

**Comment by rleigh-dundee** [comment]
Note the test failure is irrelevant--the travis checks don't cover bioformats.

**Comment by joshmoore** [comment]
Kicked travis. (Having travis test this is too time intensive?)

**Comment by rleigh-dundee** [comment]
@joshmoore If you look at http://bot.brew.sh/job/Homebrew%20Pull%20Requests/ you see they are testing a little more intelligently.  Rather than having a big test matrix; the job tests only the formulas which are updated by the PR, which greatly reduces the testing time.  It's something we might want to consider for our code (example for bioformats: if only C++ files or documentation changed; it's safe to skip the java builds, and vice versa).  For our repos, the mappings might be more complex; but it should be straightforward enough for the clear-cut cases.  Certainly for this repo, we could test just the changed formulæ.

**Comment by joshmoore** [comment]
I'll take a look, thanks. And in general, I agree with the principle, but what I'd like to find out in the homebrew case is if dependent PRs are also tested when an upstream formula changes. In our case, that's basically the build dependency graph. When, for example, Bio-Formats Java changes, then really the rest of the stack needs to be tested. On the flip side, when insight changes, it *doesn't*.

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/BIOFORMATS-cpp-5.1-merge-homebrew/1 is green, Thanks for the packaging @rleigh-dundee. Merging.

**Pull request merged**
