### PR TITLE
Add cmake dependency if OMERO is built with cpp option

### PR DESCRIPTION
**Pull request by sbesson**
See https://github.com/openmicroscopy/openmicroscopy/issues/3958

### CODE REVIEW

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/OME-5.1-merge-homebrew/171/

**Comment by rleigh-dundee** [comment]
The sha256 and cmake option changes all look fine to me.  Does this need manual testing or is this completely covered by travis+jenkins?

**Comment by sbesson** [comment]
Jenkins should be definitely checking that the build command runs when passing the `--with-cpp` option which was the issue reported in https://github.com/openmicroscopy/openmicroscopy/issues/3958. I would say CI validation is enough unless we have a simple way to check the OMERO.cpp bindings.

**Comment by rleigh-dundee** [comment]
Certainly looks good to merge to me.

**Pull request merged**
