### PR TITLE
Bump to 5.2.2

### PR DESCRIPTION
**Pull request by jburel**

### CODE REVIEW

**Comment by sbesson** [comment]
:+1: Note the `Formula/omero.rb` also needs to be amended with the same diff. How was the checksum calculated as I have `3b8f8c9b4c7a1dd10a3fd14b260a54cc1a8c7a8f253923c8a6b4735b59f4c535`?

**Comment by jburel** [comment]
sha256sum against server.

**Comment by jburel** [comment]
wrong target!!!

**Comment by jburel** [comment]
@sbesson: should be good now

**Comment by sbesson** [comment]
Looks good. Waiting for Travis and the CI to validate the formula and the installation.

**Comment by sbesson** [comment]
https://ci.openmicroscopy.org/job/OMERO-DEV-merge-homebrew/ICE=3.5,OSX=snapper/117/ is green.

**Pull request merged**
