### PR TITLE
Bio-Formats 5.2.3

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/mlfp1laZ/27-open-a-pr-to-bump-the-homebrew-formula and https://trello.com/c/5QtSmar5/52-homebrew-formula-symlinks

This PR:
- bumps the version of Bio-FOrmats to 5.2.3 with the correct shasum
- symlinks the command-line tools executables to `bin` from `libexec` (preventing `bf.sh` and `bioformats_package.jar` to be on the PATH)
- enables strict auditing of the Bio-Formats formula in `.travis.yml` and make necessary updates

### CODE REVIEW

**Comment by sbesson** [comment]
See https://ci.openmicroscopy.org/job/BIOFORMATS-DEV-merge-homebrew/53

**Comment by rleigh-codelibre** [comment]
The job is green, and everything looks OK and good to merge.

However, just as a note, I don't think this is an appropriate use of libexec.  libexec is for programs you don't want on your `PATH` *at all*, not for hiding other bits and pieces.  `jar` files shouldn't be in libexec, and neither should shell helpers.  I think if we want to package up bioformats properly, these bits should be installed into their correct places in the filesystem hierarchy, i.e. lib and share, respectively.

**Comment by sbesson** [comment]
@rleigh-codelibre thanks for the additional comments. The idea was to get one step further from the current situation where the JAR and `bf.sh` where on the PATH. Having the JAR properly installed in `lib` could be a next step before submitting the formula upstream but I suspect it will require some additional code changes.
In the meantime, should we get this PR in as it is? Otherwise, happy to update it and reduce it to the version bump and strict auditing only for this round?

**Comment by rleigh-codelibre** [comment]
I think this is OK as an incremental improvement upon what we had, and so can be merged as is, but there's room for improvement in the future.  bf.sh can be sourced from `share`, and set the classpath to use a jar from `lib` as a future change.  We might also want to go the way ome-files did, and have a different script for in-tree vs out-of-tree end use.

**Comment by rleigh-codelibre** [comment]
@sbesson Another question here is exactly what user interface we want to expose.  Right now, we're doing things a bit backwards in that all the scripts source bf.sh.  We could do this the other way around: have a single `bf` command in `bin` which runs the individual scripts from `libexec` after setting up the environment.  Or, given the nature of the Java code, have a single script which just invokes the appropriate class.  So `bf convert` can run the image converter directly without the need for extra shell scripts.

**Comment by joshmoore** [comment]
Assuming we can use the symlink trick to pick the script based on the links name:

```
ln -s .../libexec/bf /bin/bfconvert
```

**Comment by rleigh-codelibre** [comment]
@joshmoore That would probably work.  But it's not really an appropriate use of `libexec`.  It's likely easier to have a functional `bf` command in `bin` and encourage its use over the separate commands (as we do for ome-files), and phase out the separate commands.  It'll be simpler.

**Comment by sbesson** [comment]
Merging this as per https://github.com/ome/homebrew-alt/pull/111#issuecomment-251627369 and following the release. @rleigh-codelibre if you want to capture the proposed improvements and discuss the various options, feel free to file a card with a proposal.

**Comment by joshmoore** [comment]
It'll be simpler, but I think users are quite use to the commands. I'd be hesitant to deprecate them right now.

**Pull request merged**
